/*
Steampipe Cloud

Steampipe Cloud is a hosted version of Steampipe (https://steampipe.io), an open source tool to instantly query your cloud services (e.g. AWS, Azure, GCP and more) with SQL. No DB required.

API version: {{OPEN_API_VERSION}}
Contact: help@steampipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package steampipecloud

import (
	"encoding/json"
)

// ListWorkspaceAggregatorsResponse struct for ListWorkspaceAggregatorsResponse
type ListWorkspaceAggregatorsResponse struct {
	Items     *[]WorkspaceAggregator `json:"items,omitempty"`
	NextToken *string                `json:"next_token,omitempty"`
}

// NewListWorkspaceAggregatorsResponse instantiates a new ListWorkspaceAggregatorsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWorkspaceAggregatorsResponse() *ListWorkspaceAggregatorsResponse {
	this := ListWorkspaceAggregatorsResponse{}
	return &this
}

// NewListWorkspaceAggregatorsResponseWithDefaults instantiates a new ListWorkspaceAggregatorsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWorkspaceAggregatorsResponseWithDefaults() *ListWorkspaceAggregatorsResponse {
	this := ListWorkspaceAggregatorsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListWorkspaceAggregatorsResponse) GetItems() []WorkspaceAggregator {
	if o == nil || o.Items == nil {
		var ret []WorkspaceAggregator
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkspaceAggregatorsResponse) GetItemsOk() (*[]WorkspaceAggregator, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListWorkspaceAggregatorsResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []WorkspaceAggregator and assigns it to the Items field.
func (o *ListWorkspaceAggregatorsResponse) SetItems(v []WorkspaceAggregator) {
	o.Items = &v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *ListWorkspaceAggregatorsResponse) GetNextToken() string {
	if o == nil || o.NextToken == nil {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorkspaceAggregatorsResponse) GetNextTokenOk() (*string, bool) {
	if o == nil || o.NextToken == nil {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *ListWorkspaceAggregatorsResponse) HasNextToken() bool {
	if o != nil && o.NextToken != nil {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *ListWorkspaceAggregatorsResponse) SetNextToken(v string) {
	o.NextToken = &v
}

func (o ListWorkspaceAggregatorsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.NextToken != nil {
		toSerialize["next_token"] = o.NextToken
	}
	return json.Marshal(toSerialize)
}

type NullableListWorkspaceAggregatorsResponse struct {
	value *ListWorkspaceAggregatorsResponse
	isSet bool
}

func (v NullableListWorkspaceAggregatorsResponse) Get() *ListWorkspaceAggregatorsResponse {
	return v.value
}

func (v *NullableListWorkspaceAggregatorsResponse) Set(val *ListWorkspaceAggregatorsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListWorkspaceAggregatorsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListWorkspaceAggregatorsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWorkspaceAggregatorsResponse(val *ListWorkspaceAggregatorsResponse) *NullableListWorkspaceAggregatorsResponse {
	return &NullableListWorkspaceAggregatorsResponse{value: val, isSet: true}
}

func (v NullableListWorkspaceAggregatorsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWorkspaceAggregatorsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
