/*
Steampipe Cloud

Interrogate your CloudOps data with the simplicity and power of SQL, then share your discoveries using Steampipe Cloud.

API version: 1.0
Contact: help@steampipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package steampipecloud

import (
	"encoding/json"
)

// QueryWorkspaceSchema struct for QueryWorkspaceSchema
type QueryWorkspaceSchema struct {
	Duration int32             `json:"duration"`
	Schemas  []QuerySchemaInfo `json:"schemas"`
}

// NewQueryWorkspaceSchema instantiates a new QueryWorkspaceSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryWorkspaceSchema(duration int32, schemas []QuerySchemaInfo) *QueryWorkspaceSchema {
	this := QueryWorkspaceSchema{}
	this.Duration = duration
	this.Schemas = schemas
	return &this
}

// NewQueryWorkspaceSchemaWithDefaults instantiates a new QueryWorkspaceSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryWorkspaceSchemaWithDefaults() *QueryWorkspaceSchema {
	this := QueryWorkspaceSchema{}
	return &this
}

// GetDuration returns the Duration field value
func (o *QueryWorkspaceSchema) GetDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *QueryWorkspaceSchema) GetDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *QueryWorkspaceSchema) SetDuration(v int32) {
	o.Duration = v
}

// GetSchemas returns the Schemas field value
func (o *QueryWorkspaceSchema) GetSchemas() []QuerySchemaInfo {
	if o == nil {
		var ret []QuerySchemaInfo
		return ret
	}

	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value
// and a boolean to check if the value has been set.
func (o *QueryWorkspaceSchema) GetSchemasOk() (*[]QuerySchemaInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schemas, true
}

// SetSchemas sets field value
func (o *QueryWorkspaceSchema) SetSchemas(v []QuerySchemaInfo) {
	o.Schemas = v
}

func (o QueryWorkspaceSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["duration"] = o.Duration
	}
	if true {
		toSerialize["schemas"] = o.Schemas
	}
	return json.Marshal(toSerialize)
}

type NullableQueryWorkspaceSchema struct {
	value *QueryWorkspaceSchema
	isSet bool
}

func (v NullableQueryWorkspaceSchema) Get() *QueryWorkspaceSchema {
	return v.value
}

func (v *NullableQueryWorkspaceSchema) Set(val *QueryWorkspaceSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryWorkspaceSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryWorkspaceSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryWorkspaceSchema(val *QueryWorkspaceSchema) *NullableQueryWorkspaceSchema {
	return &NullableQueryWorkspaceSchema{value: val, isSet: true}
}

func (v NullableQueryWorkspaceSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryWorkspaceSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
