/*
Steampipe Cloud

Interrogate your CloudOps data with the simplicity and power of SQL, then share your discoveries using Steampipe Cloud.

API version: 1.0
Contact: help@steampipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package steampipecloud

import (
	"encoding/json"
)

// SearchUsersResponse struct for SearchUsersResponse
type SearchUsersResponse struct {
	Items     *[]UserSearch `json:"items,omitempty"`
	NextToken *string       `json:"next_token,omitempty"`
}

// NewSearchUsersResponse instantiates a new SearchUsersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchUsersResponse() *SearchUsersResponse {
	this := SearchUsersResponse{}
	return &this
}

// NewSearchUsersResponseWithDefaults instantiates a new SearchUsersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchUsersResponseWithDefaults() *SearchUsersResponse {
	this := SearchUsersResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *SearchUsersResponse) GetItems() []UserSearch {
	if o == nil || o.Items == nil {
		var ret []UserSearch
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchUsersResponse) GetItemsOk() (*[]UserSearch, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *SearchUsersResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []UserSearch and assigns it to the Items field.
func (o *SearchUsersResponse) SetItems(v []UserSearch) {
	o.Items = &v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *SearchUsersResponse) GetNextToken() string {
	if o == nil || o.NextToken == nil {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchUsersResponse) GetNextTokenOk() (*string, bool) {
	if o == nil || o.NextToken == nil {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *SearchUsersResponse) HasNextToken() bool {
	if o != nil && o.NextToken != nil {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *SearchUsersResponse) SetNextToken(v string) {
	o.NextToken = &v
}

func (o SearchUsersResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.NextToken != nil {
		toSerialize["next_token"] = o.NextToken
	}
	return json.Marshal(toSerialize)
}

type NullableSearchUsersResponse struct {
	value *SearchUsersResponse
	isSet bool
}

func (v NullableSearchUsersResponse) Get() *SearchUsersResponse {
	return v.value
}

func (v *NullableSearchUsersResponse) Set(val *SearchUsersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchUsersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchUsersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchUsersResponse(val *SearchUsersResponse) *NullableSearchUsersResponse {
	return &NullableSearchUsersResponse{value: val, isSet: true}
}

func (v NullableSearchUsersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchUsersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
